
#ifndef   _THREAD_COMPASS_SPOOFER_H_
#define   _THREAD_COMPASS_SPOOFER_H_

#include <string>
#include <cmath>

#include "localization.h"
#include "madara/threads/BaseThread.h"

namespace threads
{
  /**
  * A custom thread generated by gams_sim_conf.pl
  **/
  class compass_spoofer : public madara::threads::BaseThread
  {
  public:
    /**
     * Default constructor
     **/
    compass_spoofer (threads::localization * localization_reference);
    
    /**
     * Destructor
     **/
    virtual ~compass_spoofer ();
    
    /**
      * Initializes thread with MADARA context
      * @param   context   context for querying current program state
      **/
    virtual void init (madara::knowledge::KnowledgeBase & knowledge);

    /**
      * Executes the main thread logic
      **/
    virtual void run (void);

  private:
    /// data plane if we want to access the knowledge base
    madara::knowledge::KnowledgeBase data_;
    double angle;
    std::function<void(Datum)> new_sensor_callback;
  };
} // end namespace threads

#endif // _THREAD_COMPASS_SPOOFER_H_
