
#ifndef   _OPERATOR_WATCHDOG_H_
#define   _OPERATOR_WATCHDOG_H_

#include <string>
#include <stdio.h>

#include "madara/threads/BaseThread.h"
#include "../boat_containers.h"

namespace threads
{
  /**
  * A custom thread generated by gams_sim_conf.pl
  **/
  class operator_watchdog : public madara::threads::BaseThread
  {
  public:
    /**
     * Default constructor
     **/
    operator_watchdog (Containers & containers_);
    
    /**
     * Destructor
     **/
    virtual ~operator_watchdog ();
    
    /**
      * Initializes thread with MADARA context
      * @param   context   context for querying current program state
      **/
    virtual void init (madara::knowledge::KnowledgeBase & knowledge);

    /**
      * Executes the main thread logic
      **/
    virtual void run (void);

  private:
    /// data plane if we want to access the knowledge base
    madara::knowledge::KnowledgeBase data_;
    Containers containers;
  };
} // end namespace threads

#endif // _OPERATOR_WATCHDOG_H_
